# Generated by Django 4.0.3 on 2023-01-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicleNo', models.CharField(blank=True, max_length=250, null=True)),
                ('pourpose', models.CharField(max_length=250)),
                ('noOfPerson', models.CharField(max_length=250)),
                ('idNo', models.CharField(max_length=250)),
                ('typeOf', models.CharField(max_length=250)),
                ('personToMeet', models.CharField(max_length=250)),
                ('inTime', models.CharField(max_length=250)),
                ('allowingEntryinLicanceArea', models.CharField(max_length=250)),
                ('outTime', models.CharField(max_length=250)),
                ('permittedBy', models.CharField(max_length=250)),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
    ]
