# Generated by Django 4.0.3 on 2023-02-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatePass', '0002_gatepass_carringgadget_gatepass_passno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='thumbPrint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
