# Generated by Django 4.0.3 on 2023-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatePass', '0003_gatepass_thumbprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='thumbImage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
