# Generated by Django 4.0.3 on 2023-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatePass', '0004_gatepass_thumbimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='picture',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
