# Generated by Django 4.0.3 on 2023-03-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0012_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank',
        ),
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='delTable',
        ),
        migrations.DeleteModel(
            name='differentRemarks',
        ),
        migrations.DeleteModel(
            name='DSA',
        ),
        migrations.DeleteModel(
            name='fee',
        ),
        migrations.DeleteModel(
            name='handledBy',
        ),
        migrations.DeleteModel(
            name='registrarOffice',
        ),
    ]
